import Head from 'next/head'
import Header from '/components/core/Header'
import InventoryManagement from '/components/InventoryManagement'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Migo - CMS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main >
        <Header />
        <InventoryManagement />
      </main>

    </div>
  )
}
